include: 'https://gitlab.gnome.org/GNOME/citemplates/raw/master/flatpak/flatpak_ci_initiative.yml'

variables:
  BUNDLE: 'gnome-clocks-dev.flatpak'

flatpak:
  extends: '.flatpak'
  variables:
    MANIFEST_PATH: 'build-aux/flatpak/org.gnome.clocks.json'
    MESON_ARGS: '-Dprofile=development'
    FLATPAK_MODULE: 'gnome-clocks'
    RUNTIME_REPO: 'https://nightly.gnome.org/gnome-nightly.flatpakrepo'
    APP_ID: 'org.gnome.clocksDevel'

review:
  dependencies:
    - 'flatpak'
  extends: '.review'

stop_review:
  extends: '.stop_review'

nightly:
  extends: '.publish_nightly'
