include: 'https://gitlab.gnome.org/GNOME/citemplates/raw/master/flatpak/flatpak_ci_initiative.yml'

stages:
  - deploy

flatpak:
    image: 'registry.gitlab.gnome.org/gnome/gnome-runtime-images/gnome:master'
    variables:
        BUNDLE: "gnome-clocks-dev.flatpak"
        MANIFEST_PATH: "build-aux/flatpak/org.gnome.clocks.json"
        MESON_ARGS: "-Dprofile=development"
        FLATPAK_MODULE: "gnome-clocks"
        RUNTIME_REPO: "https://nightly.gnome.org/gnome-nightly.flatpakrepo"
        APP_ID: "org.gnome.clocksDevel"
    extends: ".flatpak"

review:
    stage: deploy
    dependencies:
        - flatpak
    script:
        - echo "Generating flatpak deployment"
    extends: '.review'

stop_review:
    stage: deploy
    script:
        - echo "Stopping flatpak deployment"
    extends: '.stop_review'

nightly:
    extends: '.publish_nightly'

lint:
  image: "valalang/lint:latest"
  stage: ".pre"
  script:
    - io.elementary.vala-lint src
